---
title: "Overview of Gameday"
author: "Craig Jones"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of Gameday}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

I did this! :)

Made some change

Vignettes are long form documentation commonly included in packages. Because they are part of the distribution of the package, they need to be as compact as possible. The `html_vignette` output type provides a custom style sheet (and tweaks some options) to ensure that the resulting html is as small as possible. The `html_vignette` format:

- Never uses retina figures
- Has a smaller default figure size
- Uses a custom CSS stylesheet instead of the default Twitter Bootstrap style

## Vignette Info

This package contains two functions. 

The first function, gday(), can be used to look up whether an NHL team is playing a game on a given date. The default team is the Vancouver Canucks and the current date is the default. Specific NHL teams can be selected by inputting the team name [gday("team name")] or by inputting the team's city [gday("team city")]. The output will be either TRUE if the team has a game on this date, or FALSE if not.

The second function, scores(), can be used to find the scores of NHL games that have taken place. The current date is the default date. The entered date must follow a yyyy-mm-dd format. 

